server {
	listen					8888;
	server_name				localhost;
	error_page				404 /errors/404.html;
	error_page				500 502 503 504 /errors/50x.html;
	client_max_body_size	10m;

	location / {
		methods		GET;
		root		/html;
		index		index.html;
		autoindex	off;
	}

	location /upload {
		methods					POST DELETE;
		root					/var/www/html;
		upload_store			/var/www/uploads;
		client_max_body_size	100m;
	}

	location /cgi-bin {
		methods	GET POST;
		root	/var/www/cgi-bin;
		cgi		.py /usr/bin/python3;
		cgi		.php /usr/bin/php-cgi;
	}
	# TEST : ceci est un commentaire ################# Fin de commentaire
	location /old-page {
		root	/html;
		methods	GET;
		return	301 /new-page;
	}
}

server {
	listen		9090;
	server_name	localhost;

	location / {
		methods		GET;
		root		/var/www/site2;
		index		index.html;
		autoindex	on;
	}
}
