server {
	listen					8080;
	server_name				localhost;
	error_page				404 /errors/404.html;
	error_page				413 /errors/413.html;
	error_page				500 502 503 504 /errors/50x.html;
	client_max_body_size	50;
	root					/var/www/html;

	location / {
		methods		GET POST DELETE;
		index		index_test.html;
		upload_store			/var/www/html/uploads;
		autoindex	on;
	}

	location /uploads {
		methods					POST DELETE GET;
		index					index.html;
		upload_store			/var/www/html/uploads;
		client_max_body_size	1k;
	}

	location /counter {
		methods	GET;
		index	index.html;
	}

	location /post_body {
		methods					POST;
		client_max_body_size	1k;
		upload_store			/YoupiBanane;
	}

	location /cgi-bin {
		methods	POST GET;
		root					/var/www/html;
		index					index.html;
		index_cgi				bad_tester;
		client_max_body_size	1k;
		upload_store			/var/www/html/;
		cgi						.py /usr/bin/python3;
		cgi						.php /usr/bin/php-cgi;
	}

	# TEST : ceci est un commentaire ################# Fin de commentaire
	location /old-page {
		methods GET;
		return	301 /new-page;
	}
}

server {
	listen		8082;
	server_name	localhost;
	root		/var/www/html;

	location /homepage {
		methods		GET;
		root		/var/www/site2;
		index		index.html;
		autoindex	on;
	}
}
