server {
	listen					8080;
	server_name				localhost;
	error_page				404 /errors/404.html;
	error_page				500 502 503 504 /errors/50x.html;
	client_max_body_size	10m;
	root					/var/www/html;

	location / {
		methods		GET;
		index		index.html;
		autoindex	on;
	}

	location /uploads {
		methods					POST DELETE GET;
		index					index.html;
		upload_store			/var/www/html/uploads;
		client_max_body_size	1k;
	}

	location /post_body {
		methods	POST;
		client_max_body_size	1k;
		upload_store	/YoupiBanane;
	}

	location /directory {
		methods GET POST DELETE;
		upload_store	/YoupiBanane;
		root	/YoupiBanane;
		client_max_body_size 1g;
		index	youpi.bad_extension;
	}

	location /cgi-bin {
		methods	GET POST;
		root	/var/www/html;
		index	index.html;
		cgi		.py /usr/bin/python3;
		cgi		.php /usr/bin/php-cgi;
	}

	# TEST : ceci est un commentaire ################# Fin de commentaire
	location /old-page {
		methods GET;
		return	301 /new-page;
	}
}

server {
	listen		9090;
	server_name	localhost;
	root		/var/www/html;

	location /homepage {
		methods		GET;
		root		/var/www/site2;
		index		index.html;
		autoindex	on;
	}
}
